server:
  port: 8082

spring:
  application:
    name: gateway

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    gateway:
      # Puedes agregar aquí la configuración de rutas, filtros, etc.
  config:
    import: optional:configserver:

  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway.security: DEBUG

eureka:
  instance:
    status-page-url-path: http://localhost:8082/actuator/info
    health-check-url-path: http://localhost:8082/actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: gateway
    description: gateway

jwt:
  secret:
    key: dGhpcyBpcyBhIHNhbXBsZSBzZWNyZXQgb3B0aW9uYWw=
  prefix: "Bearer"
