server:
  port: 8085

spring:
  application:
    name: accounts-server

  config:
    import: "optional:configserver:"

  datasource:
    url: jdbc:sqlite:./data/money-dh.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        format_sql: true

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      keycloak: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  instance:
    status-page-url-path: http://localhost:${server.port}/actuator/info
    health-check-url-path: http://localhost:${server.port}/actuator/health
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: accounts-server
