server:
  port: 8082

spring:
  application:
    name: gateway

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Request-Foo, Bar
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - X-Secret-Token

  config:
    import: "optional:configserver:"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

gateway:
  secret-token: test-secret
