spring:
  application:
    name: users-server

  datasource:
    url: jdbc:sqlite::memory:
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect

  config:
    import: optional:classpath:application.yml

eureka:
  client:
    enabled: false

logging:
  level:
    root: WARN
